### ISSUE TITLE
"The parameter is incorrect" - Unable to Add TOSEC GDI's from ZIP Files

### ISSUE THREAD

**Issue by dotdissent** [Louhike/Ugly-GDEmu-Games-Manager#74] opened 2021-05-03 22:04 UTC
The software detects the GDI's within the ZIP's but fails with error "The parameter is incorrect" when I try to copy them over. Doesn't matter if I have them set to shrink or not. It can add them if they're unzipped in the same location just fine. See screenshot.

UGGM version is 0.7.2.

![image](https://user-images.githubusercontent.com/17419460/116939151-d87b3a80-ac39-11eb-87bb-b5ddedcc539b.png)

**Comment by Louhike** [comment] 2021-05-04 18:50
Thanks for the issue, I'm gonna check that this weekend.

**Comment by Drakonas** [comment] 2021-07-01 23:05
Is it possible the issue lies with torrentzipped zip's?

**Comment by Louhike** [comment] 2022-09-10 12:16
Ok I found the reason. I managed incorrectly ZIP files. Sorry for not fixing that earlier, I could not reproduce it before. It will work in the next release (which should be released this weekend).

**Comment by Louhike** [comment] 2022-09-11 13:26
Fixed with last released version

**Closed** 2022-09-11 13:26 UTC
Labels: bug
